### ISSUE TITLE
Text Sizing

### ISSUE THREAD

**Issue by jkread** [qJake/hacc.dev#4]
Unable to modify text per tile or even per page. Theme appears to be universal to the entire set of pages.

Really love where this is going. Just started taking a look at it but wanted to point out a few things if you're open to feedback.

Thanks

**Comment by qJake** [comment]
You can use the Additional CSS Properties option on each tile to include CSS properties that affect only that tile.

See for example:

![image](https://user-images.githubusercontent.com/652006/113191342-09271900-9223-11eb-9b5d-be8790366816.png)

You can also include custom CSS in your themes which target specific tiles or types of tiles, since all tiles have appropriately named CSS classes and IDs.
